name: fastapi-handson

services:
  base:
    image: fastapi-handson:base
    build:
      context: .
      target: base
    profiles:
      - ""
    container_name: fastapi-base

  backend-dev:
    profiles:
      - development
    image: fastapi-handson:dev
    build:
      context: .
      target: development
    container_name: fastapi-dev
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fastapi
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  backend-prod:
    profiles:
      - production
    image: fastapi-handson:prod
    build:
      context: .
      target: production
    container_name: fastapi-prod
    restart: always
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fastapi
      SECRET_KEY: ${SECRET_KEY}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    container_name: fastapi-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-fastapi}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-fastapi}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
